###############################################################################
# AUTO-GENERATED FILE — DO NOT EDIT
#
# Generated by: python -m ramulator codegen
# Source:       src/ramulator/frontend/impl/memory_trace/prime_request_trace.cpp
#
# Regenerate:   python -m ramulator codegen
###############################################################################
from ramulator.components import Component
from ramulator.param import Param


class PrimeRequestTrace(Component):
    impl = "PrimeRequestTrace"
    clock_ratio = Param(int, required=True, cpp_type="unsigned int")
    path = Param(str, required=True)
